version: "3.8"

services:
  app:
    image: ghcr.io/arielmonroy392/restapp:${TAG}
    depends_on:
      - redisService
    ports:
      - "5000:${PORT}" 
    restart: unless-stopped

  redisService:
    image: redis:alpine
    ports:
      - "6379:6379"
    restart: unless-stopped
